In [1]:
import numpy as np
import pandas as pd

In [25]:
fifa_data = pd.read_csv('fifa21_train.csv')
pd.set_option('display.max_columns', 101)
display(fifa_data.head())

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,1,"Jul 1, 2015",NaN,€525K,€4K,€801K,2015 ~ 2020,258,54,47,43,70,44.0,286,61,44.0,55,63,63,346,64,73,61.0,66,82.0,306,62,73.0,71,55,45,290,54,52.0,62.0,68.0,54,54.0,148,49,56,43.0,48,7,12,14,9,6,1682,357,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,3,58+1,58+1,58+1,61+0,62+0,62+0,62+0,61+0,63+1,63+1,63+1,63+1,63+1,63+1,63+1,63+1,59+1,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,0,"Jan 16, 2015","Dec 31, 2020",€8.5M,€23K,€0,"Dec 31, 2020 On Loan",365,66,79,76,68,76.0,375,83,78.0,72,63,79,404,83,83,88.0,75,75.0,372,74,81.0,75,74,68,313,54,33.0,78.0,72.0,76,70.0,77,35,20,22.0,55,11,7,14,7,16,1961,412,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,44,77+0,77+0,77+0,77+0,77+0,77+0,77+0,77+0,76+1,76+1,76+1,76+1,68+2,68+2,68+2,76+1,57+2,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,0,"Jan 31, 2019",NaN,€9M,€49K,€15.3M,2019 ~ 2022,336,73,76,34,78,75.0,424,85,89.0,91,74,85,424,84,76,93.0,78,93.0,308,79,34.0,75,42,78,332,75,26.0,80.0,78.0,73,82.0,80,23,29,28.0,21,6,3,6,3,3,1925,404,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,73,73+2,73+2,73+2,80+0,79+0,79+0,79+0,80+0,80+0,80+0,80+0,79+1,74+2,74+2,74+2,79+1,59+2,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,13,"Jul 1, 2016",NaN,€275K,€4K,€694K,2016 ~ 2021,242,44,42,58,62,36.0,259,54,41.0,46,57,61,282,54,59,59.0,55,55.0,277,57,60.0,64,58,38,257,61,57.0,31.0,54.0,54,48.0,168,55,58,55.0,42,8,9,6,7,12,1527,329,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,7,50+2,50+2,50+2,51+0,51+0,51+0,51+0,51+0,53+2,53+2,53+2,53+2,56+2,56+2,56+2,53+2,56+2,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,8,"Jul 1, 2018",NaN,€725K,€2K,€1.4M,2018 ~ 2021,249,49,37,61,68,34.0,280,64,44.0,45,61,66,324,66,66,61.0,62,69.0,280,61,34.0,81,61,43,294,66,60.0,55.0,64.0,49,58.0,185,58,61,66.0,52,8,9,15,5,15,1664,360,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,4,56+2,56+2,56+2,59+0,59+0,59+0,59+0,59+0,61+2,61+2,61+2,62+2,63+2,63+2,63+2,62+2,64+2,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65

In [26]:
# Have a look at the datatypes of the columns:
#pd.set_option('display.max_rows', 101)
#print(fifa_data.dtypes)

In [27]:
fifa_data = fifa_data.drop(['Team & Contract','Position', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Shot Power', 'Jumping', 'Stamina', 'Long Shots', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'GK Diving', 'GK Handling', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes'], axis=1)
display(fifa_data.head())

,ID,Name,Age,Nationality,Club,BP,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Skill,Movement,Power,Strength,Mentality,Defending,Goalkeeping,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,"5'9""",161lbs,Right,1,"Jul 1, 2015",NaN,€525K,€4K,€801K,2015 ~ 2020,258,286,346,306,55,290,148,48,1682,357,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,3,58+1,58+1,58+1,61+0,62+0,62+0,62+0,61+0,63+1,63+1,63+1,63+1,63+1,63+1,63+1,63+1,59+1,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,"6'0""",159lbs,Right,0,"Jan 16, 2015","Dec 31, 2020",€8.5M,€23K,€0,"Dec 31, 2020 On Loan",365,375,404,372,74,313,77,55,1961,412,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,44,77+0,77+0,77+0,77+0,77+0,77+0,77+0,77+0,76+1,76+1,76+1,76+1,68+2,68+2,68+2,76+1,57+2,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,"5'4""",134lbs,Right,0,"Jan 31, 2019",NaN,€9M,€49K,€15.3M,2019 ~ 2022,336,424,424,308,42,332,80,21,1925,404,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,73,73+2,73+2,73+2,80+0,79+0,79+0,79+0,80+0,80+0,80+0,80+0,79+1,74+2,74+2,74+2,79+1,59+2,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,"5'10""",152lbs,Right,13,"Jul 1, 2016",NaN,€275K,€4K,€694K,2016 ~ 2021,242,259,282,277,58,257,168,42,1527,329,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,7,50+2,50+2,50+2,51+0,51+0,51+0,51+0,51+0,53+2,53+2,53+2,53+2,56+2,56+2,56+2,53+2,56+2,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,"5'11""",150lbs,Right,8,"Jul 1, 2018",NaN,€725K,€2K,€1.4M,2018 ~ 2021,249,280,324,280,61,294,185,52,1664,360,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,4,56+2,56+2,56+2,59+0,59+0,59+0,59+0,59+0,61+2,61+2,61+2,62+2,63+2,63+2,63+2,62+2,64+2,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65

In [5]:
#To get rid of the stars in the columns SM, W/F and IR print out the star and replace it:

In [28]:
print(fifa_data['SM'][0])

2★

In [29]:
#Cancel the ★ from the lines SM, W/F and IR
fifa_data['SM']=fifa_data['SM'].str.replace('★','') 
fifa_data['W/F']=fifa_data['W/F'].str.replace('★','')
fifa_data['IR']=fifa_data['IR'].str.replace('★','')

In [30]:
# Check if the stars are gone:
display(fifa_data[['SM', 'W/F', 'IR']].head())

  SM W/F  IR
0  2  4   1
1  4  3   2
2  4  4   2
3  2  2   1
4  3  2   1

In [39]:
# Replace some of the titles with more understandable titles:
fifa_data = fifa_data.rename(columns={'BP' : 'Best Position',
                                'A/W' : 'Attacking Workrate', 
                                'D/W':'Defensive Workrate', 
                                'IR' : 'International Reputation', 
                                'W/F' : 'Weak Foot', 
                                'SM' : 'Skill Move',
                                'Loan Date End' : 'On Loan'})

In [32]:
#Some of the players perform better depending on the opponent team. We can remove these values
#To get rid of the +1 etc. define a function:
def split(x):
    x=x.str.split('+', n=1, expand=True)[0]
    return x

In [33]:
fifa_data[-10:-2][:]

,ID,Name,Age,Nationality,Club,Best Position,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Skill,Movement,Power,Strength,Mentality,Defending,Goalkeeping,Total Stats,Base Stats,Weak Foot,Skill Move,Attacking Workrate,Defensive Workrate,International Reputation,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
11691,214772,N. Pasquini,29,Argentina,Estudiantes de La Plata,LB,"5'8""",168lbs,Left,0,"Feb 1, 2013","Dec 31, 2021",€2.6M,€12K,€0,"Dec 31, 2021 On Loan",309,354,348,359,68,311,204,55,1940,409,2,3,Medium,Medium,1,76,59,73,64,67,70,3,62+2,62+2,62+2,65+0,64+0,64+0,64+0,65+0,66+2,66+2,66+2,67+2,68+2,68+2,68+2,67+2,70+2,69+2,69+2,69+2,70+2,70+2,65+2,65+2,65+2,70+2,16+2,72
11692,192064,Ricardo Goulart,29,China PR,Hebei China Fortune FC,CF,"5'11""",176lbs,Right,0,"Jan 13, 2015","Jun 30, 2021",€15M,€23K,€0,"Jun 30, 2021 On Loan",386,377,390,377,70,330,112,46,2018,426,4,4,High,Medium,2,81,78,77,79,41,70,93,79+1,79+1,79+1,79+0,80+0,80+0,80+0,79+0,79+1,79+1,79+1,79+1,74+2,74+2,74+2,79+1,62+2,60+2,60+2,60+2,62+2,59+2,54+2,54+2,54+2,59+2,17+2,80
11693,214343,D. Moreno,28,Colombia,Junior FC,CDM,"5'11""",170lbs,Right,0,"Jan 1, 2020",NaN,€800K,€2K,€1.1M,2020 ~ 2021,266,256,346,302,79,288,193,54,1705,372,2,2,Medium,High,1,70,40,57,61,65,79,7,56+2,56+2,56+2,57+0,57+0,57+0,57+0,57+0,58+2,58+2,58+2,60+2,62+2,62+2,62+2,60+2,66+2,67+1,67+1,67+1,66+2,66+2,66+2,66+2,66+2,66+2,17+2,68
11694,196143,D. Pabón,32,Colombia,Monterrey,RM,"5'7""",163lbs,Right,0,"Jun 11, 2014",NaN,€5M,€37K,€8.5M,2014 ~ 2022,344,365,399,384,70,342,103,64,2001,415,4,3,High,High,2,84,76,73,73,38,71,20,74+1,74+1,74+1,75+0,75+0,75+0,75+0,75+0,75+0,75+0,75+0,74+1,70+2,70+2,70+2,74+1,60+2,59+2,59+2,59+2,60+2,57+2,52+2,52+2,52+2,57+2,19+2,75
11695,196848,I. Ávila,29,Peru,Melgar FBC,ST,"5'7""",154lbs,Right,0,"Jul 1, 2019",NaN,€550K,€500,€1.2M,2019 ~ 2021,290,283,368,303,60,254,80,60,1638,337,3,3,High,Low,1,66,68,47,66,33,57,4,65+0,65+0,65+0,61+0,63+0,63+0,63+0,61+0,60+2,60+2,60+2,58+2,53+2,53+2,53+2,58+2,46+2,45+2,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2,65
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,"6'1""",168lbs,Left,5,"Feb 8, 2018",NaN,€625K,€3K,€891K,2018 ~ 2021,224,248,333,273,68,266,184,61,1589,347,3,2,Medium,Medium,1,75,28,56,59,60,69,3,48+2,48+2,48+2,55+0,52+0,52+0,52+0,55+0,54+2,54+2,54+2,58+2,56+2,56+2,56+2,58+2,63+2,60+2,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,"6'1""",174lbs,Right,4,"Jul 1, 2019",NaN,€1.6M,€4K,€2.9M,2019 ~ 2022,84,96,237,217,64,101,41,347,1123,387,2,1,Medium,Medium,1,72,67,66,72,40,70,3,28+2,28+2,28+2,24+0,26+0,26+0,26+0,24+0,24+2,24+2,24+2,25+2,25+2,25+2,25+2,25+2,25+2,26+2,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,"5'6""",143lbs,Right,8,"Jan 23, 2019",NaN,€1.1M,€2K,€1.7M,2019 ~ 2024,286,291,388,278,37,241,62,57,1603,337,3,3,High,Medium,1,76,60,60,72,26,43,6,62+2,62+2,62+2,67+0,65+0,65+0,65+0,67+0,65+2,65+2,65+2,66+2,58+2,58+2,58+2,66+2,49+2,44+2,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67

In [34]:
# and run it for the affected columns with a for loop
split(fifa_data['ST'])

0        58
1        77
2        73
3        50
4        56
         ..
11696    48
11697    28
11698    62
11699    68
11700    64
Name: 0, Length: 11701, dtype: object

# Dealing with NaN values

In [35]:
#Have a look at the percentage of null values in a column to decide what to do about NaN values:

nulls_fifa_data = pd.DataFrame(round(fifa_data.isna().sum()/len(fifa_data),4)*100) #create a new dataframe that contains the percentages

nulls_fifa_data = nulls_fifa_data.reset_index()

nulls_fifa_data.columns = ['header_name', 'percent_null']
display(nulls_fifa_data[nulls_fifa_data['percent_null']!= 0])

           header_name  percent_null
4                 Club          0.15
10              Joined          0.35
11       Loan Date End         94.62
28  Attacking Workrate          0.50
29  Defensive Workrate          0.50

In [36]:
print(fifa_data['Loan Date End'].value_counts())

Jun 30, 2021    370
Jun 30, 2020     72
Dec 31, 2020     55
Jun 30, 2019     19
Jun 30, 2018     17
May 31, 2021     15
Dec 31, 2021     12
Jan 31, 2021     11
Jun 30, 2022      8
Jan 1, 2021       7
Nov 27, 2021      5
Jun 30, 2017      4
Nov 30, 2020      4
May 31, 2020      3
Jun 23, 2021      3
May 31, 2019      2
Jun 1, 2021       2
May 31, 2018      2
Jan 3, 2021       2
Dec 31, 2019      2
Jun 30, 2014      1
Jul 5, 2021       1
Jun 30, 2015      1
Aug 31, 2021      1
Jul 31, 2021      1
Jan 4, 2021       1
Dec 30, 2021      1
Jun 30, 2023      1
Aug 31, 2020      1
Jan 2, 2016       1
Jan 30, 2021      1
Jul 1, 2021       1
May 31, 2022      1
May 25, 2016      1
Name: Loan Date End, dtype: int64

In [37]:
fifa_data['Loan Date End']=fifa_data['Loan Date End'].fillna('Jan 01, 1900')
#fifa_data.isna().sum()

In [38]:
##print(fifa_data[fifa_data['Position'].isna()].head())
#print(fifa_data['Position'].isna().value_counts())
##print(fifa_data['Position'].unique())
#print(fifa_data['Position'].value_counts())
#

KeyError: 'Position'

In [17]:
#Drop the lines where positions are NaN. There are so many different positions and the lines with NaN are just about 3 %
#display(fifa_data.shape)
fifa_data = fifa_data [fifa_data['Position'].isna()==False]
display(fifa_data.shape)

(11413, 67)

In [18]:
#Have a look at the percentage of null values in a column to decide what to do about NaN values:

nulls_fifa_data = pd.DataFrame(round(fifa_data.isna().sum()/len(fifa_data),4)*100) #create a new dataframe that contains the percentages

nulls_fifa_data = nulls_fifa_data.reset_index()

nulls_fifa_data.columns = ['header_name', 'percent_null']
display(nulls_fifa_data[nulls_fifa_data['percent_null']!= 0])

           header_name  percent_null
4                 Club          0.13
11              Joined          0.24
29  Attacking Workrate          0.32
30  Defensive Workrate          0.32

In [19]:
display(fifa_data.shape)
fifa_data = fifa_data [fifa_data['Joined'].isna()==False]
display(fifa_data.shape)

(11413, 67)

(11386, 67)

In [20]:
display(fifa_data.shape)
fifa_data = fifa_data [fifa_data['Attacking Workrate'].isna()==False]
display(fifa_data.shape)

(11386, 67)

(11376, 67)

In [21]:
display(fifa_data.shape)
fifa_data = fifa_data [fifa_data['Club'].isna()==False]
display(fifa_data.shape)

(11376, 67)

(11362, 67)

In [22]:
print(fifa_data['Composure'].unique())
print(fifa_data['Composure'].value_counts())

KeyError: 'Composure'

In [ ]:
fifa_data['Composure']=fifa_data['Composure'].fillna(round(fifa_data['Composure'].mean()))